<Project Sdk="Uno.Sdk">
	<PropertyGroup>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">net9.0-android;net9.0-browserwasm;net9.0-desktop</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">net9.0-ios;net9.0-desktop</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Linux'))">net9.0-desktop</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<UnoSingleProject>true</UnoSingleProject>

		<ApplicationTitle>Restatify Support Chat</ApplicationTitle>
		<AssemblyTitle>Restatify Support Chat</AssemblyTitle>
		<Product>Restatify Support Chat</Product>
		<ApplicationIcon>Assets\Icons\restatify_logo.ico</ApplicationIcon>
		<UnoIconForegroundFile>Assets\Icons\icon_foreground.svg</UnoIconForegroundFile>
		<UnoIconForegroundScale>1.00</UnoIconForegroundScale>
		<UnoIconBackgroundColor>#FFFFFF</UnoIconBackgroundColor>
		<ApplicationId>tech.restatify.supportchat</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationPublisher>Restatify</ApplicationPublisher>
		<Description>Restatify Support Chat powered by Uno Platform.</Description>

		<UnoFeatures>
			SkiaRenderer;
		</UnoFeatures>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Uno.Dsp.Tasks" Version="1.0.1" />
		<PackageReference Include="Uno.Extensions.Configuration" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Http" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Http.Refit" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Logging.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Logging.Serilog" Version="2.3.10" />
		<PackageReference Include="Uno.Extensions.Serialization.Http" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Serialization.Refit" Version="5.2.7" />
		<PackageReference Include="Uno.Material.WinUI" Version="5.4.0" />
		<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="6.4.3" />
		<PackageReference Include="Uno.Toolkit.WinUI" Version="8.4.2" />
		<PackageReference Include="Uno.Extensions.Authentication.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Hosting.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Localization.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="5.2.7" />
		<PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="5.2.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Restatify.SupportChat.DataContracts\Restatify.SupportChat.DataContracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Assets\Icons\restatify_logo.ico" CopyToOutputDirectory="PreserveNewest" />
		<UnoDspImportColors Include="Styles\*.zip" Generator="Xaml" />
		<UnoImage Include="Assets\**\*.svg" />
		<UnoImage Include="Assets\**\*.png" />
		<EmbeddedResource Include="appsettings.json" />
		<EmbeddedResource Include="appsettings.*.json" DependentUpon="appsettings.json" />
	</ItemGroup>

	<Target Name="KillStaleDesktopProcess" BeforeTargets="Build" Condition="$([MSBuild]::IsOSPlatform('Windows')) and '$(TargetFramework)' == 'net9.0-desktop'">
		<Exec Command="taskkill /F /IM Restatify.SupportChat.Windows.exe /T" IgnoreExitCode="true" />
	</Target>
</Project>
